---
- hosts: localhost
  tasks:
    - name: update all packages
      apt:
        upgrade: dist
    - name: install all basic packages
      apt:
        name: ufw,tor,cryptsetup,xfsprogs,deluged,deluge-web,deluge-console,mate-desktop-environment-core,tightvncserver,firefox-esr
        state: latest
    - name: sshd config
      lineinfile:
        name: /etc/ssh/sshd_config
        regexp: '^AllowTcpForwarding'
        insertafter: '#AllowTcpForwarding'
        line: 'AllowTcpForwarding yes'
    - name: restart sshd
      service: name=sshd state=restarted
    - name: reconfigure tor
      blockinfile:
        name: /etc/tor/torrc
        block: |
          SocksTimeout 300
          CircuitStreamTimeout 300
          CircuitIdleTimeout 600
    - name: restart tor
      service: name=tor state=restarted enabled=yes
    - name: ufw firewall rule
      ufw:
        rule: allow
        port: ssh
        proto: tcp
    - ufw:
        policy: allow
        direction: outgoing
    - ufw:
        policy: deny
        direction: incoming
    - ufw:
        state: enabled
    - user:
        name: user
    - name: run deluge
      shell: |
        deluged
        deluge-web -f
        vncserver :5
      become: true
      become_user: user

