---
- hosts: localhost
  tasks:
    - name: update all packages
      apt:
        upgrade: dist
    - name: install all basic packages
      apt:
        name: ufw,nginx,cryptsetup,xfsprogs
        state: latest
    - name: ensure nginx is running (and enable it at boot)
      service: name=nginx state=started enabled=yes
    - name: sshd config
      lineinfile:
        name: /etc/ssh/sshd_config
        regexp: '^AllowTcpForwarding'
        insertafter: '#AllowTcpForwarding'
        line: 'AllowTcpForwarding yes'
    - name: restart sshd
      service: name=sshd state=restarted
    - name: ufw firewall rule
      ufw:
        rule: allow
        port: ssh
        proto: tcp
    - ufw:
        rule: allow
        port: http
        proto: tcp
    - ufw:
        policy: allow
        direction: outgoing
    - ufw:
        policy: allow
        direction: incoming
    - ufw:
        state: enabled
    - pip:
        name: uwsgi,virtualenv,virtualenvwrapper
    - pip:
        name: django,uwsgi
        virtualenv: /var/myapps/djangosite
    - pip:
        name: flask,uwsgi
        virtualenv: /var/myapps/flasksite
	## Install postgre for Django
	- name: install postgresql
	  apt:
	    name: postgresql
		state: latest
