---
- hosts: localhost
  vars:
    wireguard_wg0:
      priv_key: "privkey"
      ipaddr: "127.0.0.1"
      netmask: "8"
      port: "54321"
      peers:
        - { pub_key: "pub_key", endpoint: "127.0.0.2:54321", allowedips: "127.0.0.1/28"}
  tasks:
    - name: update all packages
      apt:
        upgrade: dist
    - name: install all basic packages
      apt:
        name: python3-apt,fail2ban,firewalld
        state: latest
    - name: install all pip3 dependecies
      pip:
        name:
    - name: set new repository
      apt_repository:
        repo: deb http://deb.debian.org/debian/ unstable main
        state: present
    - name: set unstable priority
      blockinfile:
        name: /etc/apt/preferences.d/limit-unstable
        create: yes
        block: |
          Package: *
          Pin: release a=unstable
          Pin-Priority: 150
    - name: install required packages
      apt:
        name: wireguard,linux-headers-amd64,nfs-common
        state: latest
    - name: set firewalld
      firewalld:
        zone: public
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: yes
      loop:
        - ssh
        - dhcpv6-client
    - name: set firewalld ports
      firewalld:
        zone: public
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: yes
      loop:
        - 54321/tcp
        - 54321/udp
    - name: set firewalld default rule
      command: firewall-cmd --permanent --zone=public --set-target=DROP
    - name: restart firewalld
      command: firewall-cmd --reload
    - include_tasks: setup-wireguard.yml
      when: '"wg0" not in ansible_interfaces'
    - name: test connection to 192.168.100.1
      command: ping 192.168.100.1 -c1
      register: ping_result
    - name: mount nfs
      mount:
        path: /root/nfs
        src: 192.168.100.1:/root/nfs
        fstype: nfs4
        state: mounted
      when: ping_result is success